# -*- coding: utf-8 -*-
"""1_supervied_learning_model-50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vWup_TuRcAf--FI03Bh04hrhtuM8gf_e

##Download data
"""

"""## Trainning model"""

from rfdetr import RFDETRBase
import platform
import torch
import os

current_path = os.getcwd()
DATASET_DIR = os.path.join(current_path, "dataset")
IMAGES_DIR = os.path.join(DATASET_DIR, "images")
ANNOTATIONS_DIR = os.path.join(DATASET_DIR, "annotations")
OUTPUT_JSON = os.path.join(DATASET_DIR,"dataset_coco.json")

# Will be saved under results folder
MODEL_SAVE_PATH = "sample_model.pth"


# Initialize the RFDETR model
model = RFDETRBase(num_classes=3, pretrained=False)

# Train using the built-in train() method
model.train(
    dataset_dir=DATASET_DIR,       # Important: RFDETR expects train/valid subfolders and _annotations.coco.json inside this path
    epochs=80,
    batch_size=4,
    lr=1e-4,
    save_path=os.path.join("..", "results", MODEL_SAVE_PATH)
)

import matplotlib.pyplot as plt

# Create data for each epoch's evaluation
# epochs = [0, 1, 2]
# ap_50_95 = [0.259, 0.384, 0.033]  # Average Precision @[ IoU=0.50:0.95 ]
# ap_50 = [0.451, 0.621, 0.062]     # Average Precision @[ IoU=0.50 ]

# Plotting
# plt.figure(figsize=(10, 6))
# plt.plot(epochs, ap_50_95, marker='o', label='AP@[0.50:0.95]')
# plt.plot(epochs, ap_50, marker='s', label='AP@0.50')

# plt.title('Average Precision Across Epochs')
# plt.xlabel('Epoch')
# plt.ylabel('Average Precision (AP)')
# plt.xticks(epochs)
# plt.legend()
# plt.grid(True)
# plt.tight_layout()
# plt.show()

"""## Test one image"""

import matplotlib.patches as patches
from PIL import Image

# Open the image and ensure it's converted to RGB (3 channels)
image = Image.open(os.path.join(DATASET_DIR, 'test/maksssksksss164.png')).convert("RGB")

# Use the model to perform prediction
detections = model.predict(image)

# Display the image with bounding boxes
fig, ax = plt.subplots(1)
ax.imshow(image)

# Define class names (customize if needed)
class_names = ["with_mask", "without_mask", "mask_weared_incorrect"]

# Iterate through the detection results
for bbox, score, class_id in zip(
    detections.xyxy, detections.confidence, detections.class_id
):
    if score < 0.5:  # Confidence threshold (adjustable)
        continue

    # Convert from xyxy to x, y, width, height
    x1, y1, x2, y2 = bbox
    x, y, w, h = x1, y1, x2 - x1, y2 - y1

    # Draw the bounding box
    rect = patches.Rectangle((x, y), w, h, linewidth=2, edgecolor='r', facecolor='none')
    ax.add_patch(rect)

    # Display the label with class name and confidence score
    label = f"{class_names[int(class_id)]}: {score:.2f}"
    ax.text(x, y, label, color='r', fontsize=10, bbox=dict(facecolor='white', alpha=0.5))

# Hide axis ticks and labels
plt.axis('off')
plt.show()

"""## Predict test set"""

from tqdm import tqdm
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval
import json

# Set path to test folder and annotations
TEST_DIR = os.path.join(DATASET_DIR, "test")
ANNOTATION_FILE = os.path.join(TEST_DIR, '_annotations.coco.json')

# Load COCO ground truth annotations
coco_gt = COCO(ANNOTATION_FILE)

# Prepare list to store predictions in COCO format
coco_predictions = []

image_ids = coco_gt.getImgIds()
class_names = ["with_mask", "without_mask", "mask_weared_incorrect"]

for img_id in tqdm(image_ids, desc="Evaluating"):
    img_info = coco_gt.loadImgs(img_id)[0]
    image_path = os.path.join(TEST_DIR, img_info['file_name'])

    # Load and convert image
    image = Image.open(image_path).convert("RGB")
    detections = model.predict(image)

    for bbox, score, class_id in zip(
        detections.xyxy, detections.confidence, detections.class_id
    ):
        if score < 0.05:
            continue  # skip low-score predictions

        # Convert bbox from xyxy to COCO format (x, y, width, height)
        x1, y1, x2, y2 = bbox
        x, y, w, h = float(x1), float(y1), float(x2 - x1), float(y2 - y1)

        coco_predictions.append({
            "image_id": img_id,
            "category_id": int(class_id),
            "bbox": [x, y, w, h],
            "score": float(score)
        })

# Save predictions to JSON
pred_path = "test_predictions.json"
with open(pred_path, "w") as f:
    json.dump(coco_predictions, f)

# Load predictions and run COCO evaluation
coco_dt = coco_gt.loadRes(pred_path)
coco_eval = COCOeval(coco_gt, coco_dt, iouType='bbox')
coco_eval.evaluate()
coco_eval.accumulate()
coco_eval.summarize()

import os
import numpy as np
from PIL import Image
from tqdm import tqdm
from pycocotools.coco import COCO
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Load COCO annotations
coco_gt = COCO(ANNOTATION_FILE)
image_ids = coco_gt.getImgIds()
class_names = ["with_mask", "without_mask", "mask_weared_incorrect"]

# Containers for true and predicted labels
y_true = []
y_pred = []

# IoU threshold for matching
def compute_iou(boxA, boxB):
    xA = max(boxA[0], boxB[0])
    yA = max(boxA[1], boxB[1])
    xB = min(boxA[0] + boxA[2], boxB[0] + boxB[2])
    yB = min(boxA[1] + boxA[3], boxB[1] + boxB[3])

    interArea = max(0, xB - xA) * max(0, yB - yA)
    boxAArea = boxA[2] * boxA[3]
    boxBArea = boxB[2] * boxB[3]
    iou = interArea / float(boxAArea + boxBArea - interArea)
    return iou

# Loop through test images
for img_id in tqdm(image_ids, desc="Building confusion matrix"):
    img_info = coco_gt.loadImgs(img_id)[0]
    image_path = os.path.join(TEST_DIR, img_info['file_name'])

    image = Image.open(image_path).convert("RGB")
    detections = model.predict(image)

    # Get ground truth boxes and labels
    ann_ids = coco_gt.getAnnIds(imgIds=img_id)
    anns = coco_gt.loadAnns(ann_ids)
    gt_boxes = [ann['bbox'] for ann in anns]
    gt_labels = [ann['category_id'] for ann in anns]

    matched_gt = set()

    # Match predictions to ground truths by IoU
    for bbox, score, pred_class in zip(
        detections.xyxy, detections.confidence, detections.class_id
    ):
        if score < 0.3:
            continue

        x1, y1, x2, y2 = bbox
        pred_box = [float(x1), float(y1), float(x2 - x1), float(y2 - y1)]
        best_iou = 0
        best_idx = -1

        for i, gt_box in enumerate(gt_boxes):
            if i in matched_gt:
                continue
            iou = compute_iou(pred_box, gt_box)
            if iou > best_iou:
                best_iou = iou
                best_idx = i

        if best_iou >= 0.5 and best_idx >= 0:
            y_true.append(gt_labels[best_idx])
            y_pred.append(int(pred_class))
            matched_gt.add(best_idx)

# Compute and plot confusion matrix
cm = confusion_matrix(y_true, y_pred, labels=[0, 1, 2])
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
disp.plot(cmap='Blues', values_format='d')
plt.xticks(rotation=45)
plt.title("Confusion Matrix on Test Set")
plt.show()
